### PR TITLE
Added in missing requirement

### PR DESCRIPTION
**Pull request by brechmos-stsci**
Checklist
* [x] Used a fork of the feedstock to propose changes
* [x] Bumped the build number (if the version is unchanged)
* [x] Reset the build number to `0` (if the version changed)
* [ ] [Re-rendered]( https://conda-forge.org/docs/conda_smithy.html#how-to-re-render ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

This was needed as it is dependent on `astropy-healpix` but was not set as a requirement.

### CODE REVIEW

**Comment by bsipocz** [comment]
cc @keflavich @cdeil @sushobhana - is healpix now a required dependency? looking at the released code it's not seemed to be used anywhere.

**Comment by brechmos-stsci** [comment]
just fyi... I assumed it from the message `The 'astropy-healpix' distribution was not found and is required by regions` when I tried to use astropy-regions.  I talked with @astrofrog-conda-forge about it too.  So, I might be incorrect on where the problem might lie.

**Comment by bsipocz** [comment]
@brechmos-stsci - I didn't mean this PR is not needed, in fact healpix is listed as an install dependency. 
Yet I don't see where it's actually being used. Or whether it indeed needs to be a hard dependency rather than an optional one.

**Comment by cdeil** [comment]
The `astropy-healpix` dependency for `regions` indeed isn't used at the moment.

It was added in https://github.com/astropy/regions/pull/212 as a first step, because for https://github.com/astropy/regions/pull/219 that should land and ship with the next release it will be needed.

I'm +1 to make it a required dependency, not an optional one.

So proceed here as you like: you can merge this PR now, and already have the conda build prepared. Or close this PR, and we add the dependency after the next release.

**Comment by bsipocz** [comment]
Other than doing a post release, I don't think there is a way to avoid merging this in. As @brechmos-stsci  mentioned, there is an error already when healpix is not installed.
It's pity that astropy/regions#212 wasn't part of astropy/regions#219, or at least didn't end up in the same release.

I'm -1 on making it a hard dependency, the current regions package already provides quite good functionality and for using those functionalities we shouldn't really propagate the dependency of healpix downstream to e.g. photutils and specutils. But if both regions and healpix end up in astropy core during the next 1 or 2 release cycles, then this preference doesn't really matter that much.

**Comment by cdeil** [comment]
OK, then go ahead and merge this in.

>  if both regions and healpix end up in astropy core during the next 1 or 2 release cycles

That's the way to go.

> I assumed it from the message The 'astropy-healpix' distribution was not found and is required by regions when I tried to use astropy-regions.

So the only issue that triggered this PR is an info printout?
Or is there an actual problem that install or import fails?
(If so, please post commands and console output to reproduce)

**Comment by brechmos-stsci** [comment]
@cdeil For our application (mosviz) I do an install and then when I run our application I am getting:
```
Traceback (most recent call last):
  File "/Users/crjones/miniconda3/envs/deleteme/bin/mosviz", line 6, in <module>
    from pkg_resources import load_entry_point
  File "/Users/crjones/miniconda3/envs/deleteme/lib/python3.6/site-packages/pkg_resources/__init__.py", line 3112, in <module>
    @_call_aside
  File "/Users/crjones/miniconda3/envs/deleteme/lib/python3.6/site-packages/pkg_resources/__init__.py", line 3096, in _call_aside
    f(*args, **kwargs)
  File "/Users/crjones/miniconda3/envs/deleteme/lib/python3.6/site-packages/pkg_resources/__init__.py", line 3125, in _initialize_master_working_set
    working_set = WorkingSet._build_master()
  File "/Users/crjones/miniconda3/envs/deleteme/lib/python3.6/site-packages/pkg_resources/__init__.py", line 578, in _build_master
    ws.require(__requires__)
  File "/Users/crjones/miniconda3/envs/deleteme/lib/python3.6/site-packages/pkg_resources/__init__.py", line 895, in require
    needed = self.resolve(parse_requirements(requirements))
  File "/Users/crjones/miniconda3/envs/deleteme/lib/python3.6/site-packages/pkg_resources/__init__.py", line 781, in resolve
    raise DistributionNotFound(req, requirers)
pkg_resources.DistributionNotFound: The 'astropy-healpix' distribution was not found and is required by regions
```
which actually does not seem that useful :).

If you need something more concrete I can see about figuring out exactly where it is failing as I understand the above is not super useful.

**Comment by cdeil** [comment]
I'm not sure why `pkg_resources.DistributionNotFound` occurs on your `/Users/crjones/miniconda3/envs/deleteme/bin/mosviz` execute.

But OK.

We merge this PR and that should resolve the issue, no?

**Comment by brechmos-stsci** [comment]
In my environment above, if I next do `pip install astropy-healpix` and then run mosviz everything appears to run just fine.  So, I _assume_ by adding the install requirement for `astropy-healpix` to regions then it should install fine.

**Comment by cdeil** [comment]
@bsipocz - Can you please merge this PR?

If you want, you can also add me as maintainer for this recipe.

**Comment by bsipocz** [comment]
Both done.

**Comment by cdeil** [comment]
@brechmos-stsci - FYI: we changed course for now and decided to keep `astropy-regions` independent of `astropy-healpix` (`mocpy` would remain a separate package combining the two).

The regions v0.4 release from today no longer lists `astropy-healpix` as a dependency of `astropy-regions`, and in the conda recipe I just did the change now in
https://github.com/conda-forge/regions-feedstock/pull/9/commits/410a4f381ef037780605a5a38211b4882f3f6801 which I'll merge if CI passes.

**Pull request merged**
